services:
  # ----------------------------------------------------
  # PostgreSQL Database
  # ----------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: gurukul
      POSTGRES_PASSWORD: tutor
      POSTGRES_DB: gurukul_db
    ports:
      - "5433:5432"
    volumes:
#      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - dev-network
    restart: unless-stopped

  # ----------------------------------------------------
  # Apache Kafka (KRaft Mode)
  # ----------------------------------------------------
  kafka:
    image: apache/kafka:4.3.0
    container_name: kafka_broker
    ports:
      - "9092:9092"   # Internal Docker network port
      - "29092:29092" # External host machine port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data' # Point this to your mounted volume instead of /tmp
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CLUSTER_ID: '4L62YDgNTmqny9StEx7Tqg' # Changed to a valid 22-character base64 ID
    volumes:
      - kafka_volume:/var/lib/kafka/data
    networks:
      - dev-network
    restart: unless-stopped

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/postgres_data

  kafka_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/kafka_data