spring:
  application:
    name: user-service
  datasource:
    # Connects via localhost:5433 to map to your docker postgres_db instance
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/gurukul_db
    username: ${DB_USER:gurukul}
    password: ${DB_PASSWORD:tutor}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update # Automatically creates/updates database tables based on entity definitions
      show-sql: true     # Prints SQL logs to the console (highly useful for local debugging)
      properties:
        hibernate:
          format_sql: true # Formats the console SQL logs so they are easy to read

server:
  port: 8090