spring:
  sql:
    init:
      mode: always
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/${DB_NAME:gurukul_db}
    username: ${DB_USER:gurukul}
    password: ${DB_PASSWORD:tutor}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    # In Spring Boot 4, use vendor-properties directly to pass actions straight to Hibernate 7
    vendor-properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090